# Generated by Django 4.2.4 on 2023-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('kasarkode', 'kasarkode'), ('kannur', 'kannur'), ('kozhikode', 'kozhikode'), ('malappuram', 'malappuram'), ('wayanad', 'wayanad'), ('palakkad', 'palakkad'), ('idukki', 'idukki'), ('thrissur', 'thrissur'), ('eranakulam', 'eranakulam'), ('alappuzha', 'alappuzha'), ('pathanamthitta', 'pathanamthitta'), ('kollam', 'kollam'), ('kottayam', 'kottayam'), ('thiruvananthapuram', 'thiruvananthapuram')], default='kannur', max_length=100)),
                ('cent', models.IntegerField()),
                ('building', models.BooleanField()),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('descripton', models.CharField(max_length=500)),
            ],
        ),
    ]
