# Generated by Django 4.2.4 on 2023-09-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_broker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='img2',
            field=models.ImageField(null=True, upload_to='property_image', verbose_name='Property Image_2'),
        ),
        migrations.AddField(
            model_name='property',
            name='img3',
            field=models.ImageField(null=True, upload_to='property_image', verbose_name='Property Image_3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(default=None, upload_to='property_image', verbose_name='Property Image_1'),
        ),
    ]
